### PR TITLE
add delete functionality

### PR DESCRIPTION
**Pull request by nicwest**
ref #14 

As of yet I haven't deleted the entire contents of my hard drive. However I've still set the default command for deleting directories to `rm -r` instead of `rm -rf` because I'm scared.

@jeetsukumaran can you look this over and check I'm not doing anything retarded?

### CODE REVIEW

**Comment by jeetsukumaran** [comment]
Hi Nic,

Thanks for this. I will be honest: the main reason I've resisted adding this functionality is due to a number of design issues that need to be considered. 

One is, of course, safety, like you have noted here. The ability to wipe entire directory trees using "rm" (i.e., not just move to a temp location like "``~/.Trash``" is a little scary, especially when it is just one key-stroke. Working with remote machines with lots of lag, sometimes you miss a key while typing and you end up sending the wrong sequence. E.g., it is easy to hit "`-`" and open up FileBeagle and then find yourself in a place where you can easily send the delete commands. Sure, it is unlikely, and the joint probability of that happening followed by the confirmation is low. But the cost of that happening is so high, that the risk must be assessed as non-trivial! To this end, I would almost prefer it being a command rather than a key-mapping, to enforce the deliberateness of it (e.g., "``FileBeagleDelete``"). Perhaps the key-maps can be unassigned by default as well. 

But there is more ...

The other is cross-platform support. Your current implementation, which assumes POSIX, and expects users to update the global option if otherwise takes care of that (though perhaps a more Windows-friendly option may set ``g:filebeagle_remove_directory_command`` to an operating-system-appropriate default if not explicitly set by user.

The other is actually related to the above two: cross-platform safety. In particular all those corner cases with weird path names. Can we rely on ``shellescape`` to correctly work in all circumstances, including if there are slashes (or mixed slashes), quotes, spaces, etc. in the filepaths? If you look at some of the closed issues you will see getting existing things to work right with some Windows paths took quite a bit of fine-tuning (dealing with, e.g. "``C:\``" etc.).

Then there is the issue of what should happen if anything deleted was already being viewed/loaded in existing buffers, either FileBeagle or otherwise. Should they be removed? If a FileBeagle directory buffer, how will it be communicated to the buffer instance that the directory is no longer valid (or, if a parent directory, it needs to be refreshed)?

**Comment by nicwest** [comment]
I agree.

maybe a route like #11 makes more sense then, and design it around https://github.com/tpope/vim-eunuch or similar.

Something like:
`:FileBeagleDo :Remove`
Becomes:
 `:Remove <path-under-cursor>`

a user could bind their own commands as they want/need them
clears up most of the above issues.

**Comment by jeetsukumaran** [comment]
I think that would be the way to go. I am afraid that I will not have time to delve into this soon, however. :(

**Comment by nicwest** [comment]
I'll probably get to it at some point.

going to close this.

**Pull request closed without merging**
